
# Navbar Menus
[[main]]
name = "Service"
url = "service/"
weight = 1

[[main]]
name = "Blog"
url = "blog/"
weight = 2

[[main]]
name = "About"
url = "about/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4
