
# Navbar Menus
[[main]]
name = "(907) 519-8577"
url = "tel:+19075198577"
weight = 1
[[main]]
name = "Home"
url = "/"
weight = 2

[[main]]
name = "About"
url = "about/"
weight = 3

[[main]]
name = "Service"
url = "service/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6
