networks:
  traefik:
    external: true
services:
  hugo_site:
    build:
      context: .
      args:
        HUGO_BASEURL: ${HUGO_BASEURL:-http://localhost:8888}
    image: beardedtek/${SITE_LABEL:-hugo_site}:dc-build
    container_name: "${SITE_LABEL:-hugo_site}"
    restart: unless-stopped
    networks:
      traefik:
    ports:
      - 8888:80
    environment:
      - SERVER_ROOT=/public
      - SERVER_LOG_LEVEL=${SERVER_LOG_LEVEL:-info}
      - SERVER_HEALTH=true
      - SERVER_CORS_ALLOW_ORIGINS=${HUGO_BASEURL:-http://localhost:8888}
      - SERVER_CORS_ALLOW_HEADERS="origin, content-type, x-requested-with"
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE:-true}"
      - "traefik.docker.network=traefik}"
      - "traefik.http.routers.${SITE_LABEL:-hugo_site}.rule=Host(`${SITE_DOMAIN:-localhost}`)"
      - "traefik.http.routers.${SITE_LABEL:-hugo_site}.entryPoints=https"
      - "traefik.http.routers.${SITE_LABEL:-hugo_site}.tls=true"
      - "traefik.http.routers.${SITE_LABEL:-hugo_site}.tls.certresolver=le"
      - "traefik.http.routers.${SITE_LABEL:-hugo_site}.service=${SITE_LABEL:-hugo_site}-entrypoint"
      - "traefik.http.services.${SITE_LABEL:-hugo_site}-entrypoint.loadbalancer.server.port=80"

      - "traefik.http.middlewares.cors-header.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.cors-header.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors-header.headers.accesscontrolalloworiginlist=https://hugo.beardedtek.com"
      - "traefik.http.middlewares.cors-header.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors-header.headers.addvaryheader=true"
      - "traefik.http.routers.your-service-name.middlewares=cors-header"