networks:
  traefik:
    external: true

services:
  hugo_site:
    build:
      context: .
      args:
        GIT_REPO: ${GIT_REPO}
        HUGO_BASEURL: $HUGO_BASEURL
        HUGO_OUTPUT: ${HUGO_OUTPUT}
    image: beardetek/${TRAEFIK_LABEL:-hugo_site}
    container_name: ${TRAEFIK_LABEL:-hugo_site}
    restart: unless-stopped
    networks:
      traefik:
    ports:
      - 8888:80
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE:-true}"
      - "traefik.docker.network=traefik}"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo_site}.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo_site}.entryPoints=https"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo_site}.tls=true"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo_site}.tls.certresolver=le"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo_site}.service=${TRAEFIK_LABEL:-hugo_site}-entrypoint"
      - "traefik.http.services.${TRAEFIK_LABEL:-hugo_site}-entrypoint.loadbalancer.server.port=80"
      - "traefik.http.middlewares.cors-header.headers.accesscontrolallowmethods=GET,POST,PUT,OPTIONS"

      - "traefik.http.middlewares.cors-header.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors-header.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors-header.headers.accesscontrolmaxage=100"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo_site}.middlewares=cors-header"
