networks:
  traefik:
    external: true

services:
  hugo_nginx:
    build:
      context: .
      args:
        HUGO_BASEURL: https://hugo.beardedtek.com
    image: beardedtek/hugo-nginx
    restart: unless-stopped
    networks:
      traefik:
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE:-true}"
      - "traefik.docker.network=traefik}"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo-nginx}.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo-nginx}.entryPoints=https"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo-nginx}.tls=true"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo-nginx}.tls.certresolver=le"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo-nginx}.service=${TRAEFIK_LABEL:-hugo-nginx}-entrypoint"
      - "traefik.http.services.${TRAEFIK_LABEL:-hugo-nginx}-entrypoint.loadbalancer.server.port=80"
      - "traefik.http.middlewares.cors-header.headers.accesscontrolallowmethods=GET,POST,PUT,OPTIONS"

      - "traefik.http.middlewares.cors-header.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors-header.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors-header.headers.accesscontrolmaxage=100"
      - "traefik.http.routers.${TRAEFIK_LABEL:-hugo-nginx}.middlewares=cors-header"

